### ISSUE TITLE
SolidQueueUi::Web not defined

### ISSUE THREAD

**Issue by francis** [claudey/solid_queue_ui#1]
I followed your installation instructions, but the constant `Web` is undefined, so it of course blows up.

```
3.3.0 :001 > defined?(SolidQueueUi)
 => "constant"
3.3.0 :002 > defined?(SolidQueueUi::Web)
 => nil
```

Do we need a require somewhere?

**Comment by francis** [comment]
I have confirmed that a require does fix this:

```
authenticated :user, ->(u) { u.admin? } do
    require 'solid_queue_ui/web'
    mount SolidQueueUi::Web => '/solid_queue_ui'
    ...
```

**Comment by claudey** [comment]
🤦🏽 You're absolutely right, @francis. I forgot to add that tho the README. I don't know how I missed it. Adding now. Thanks for this.
